In [1]:
import numpy as np
import pandas as pd

In [11]:
# Q1 - Version of NumPy

np.__version__

'1.21.5'

In [100]:
df = pd.read_csv('data.csv')
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [101]:
# Q2 - Number of records in the dataset

df.shape[0]

11914

In [22]:
# Q3 - The most popular car manufacturers

df.groupby(['Make']).count().sort_values(by='Model', ascending=False).head(3)

Model  Year  Engine Fuel Type  Engine HP  Engine Cylinders  \
Make                                                                     
Chevrolet    1123  1123              1123       1117              1121   
Ford          881   881               881        868               881   
Volkswagen    809   809               809        809               805   

            Transmission Type  Driven_Wheels  Number of Doors  \
Make                                                            
Chevrolet                1123           1123             1123   
Ford                      881            881              881   
Volkswagen                809            809              809   

            Market Category  Vehicle Size  Vehicle Style  highway MPG  \
Make                                                                    
Chevrolet               622          1123           1123         1123   
Ford                    499           881            881          881   
Volkswagen              585           809            809          809   

            city mpg  Popularity  MSRP  
Make                                    
Chevrolet       1123        1123  1123  
Ford             881         881   881  
Volkswagen       809         809   809

### Uniquie Audi Models

In [27]:
# Q4 - Number of Unique Audi Models

df[df.Make == "Audi"][~df["Model"].duplicated()][['Model']].count()

/var/folders/q7/2w2rg7qx3q73nkzg9jdqrdtc0000gn/T/ipykernel_840/3548708103.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df.Make == "Audi"][~df["Model"].duplicated()][['Model']].count()


Model    34
dtype: int64

In [29]:
# Q5 - Number of columns with missing values

df.isna().sum().loc[lambda x: x>1]

Engine Fuel Type       3
Engine HP             69
Engine Cylinders      30
Number of Doors        6
Market Category     3742
dtype: int64

In [30]:
# Q6 - Does the median value change after filling missing values?
# Median value before filling missing values:

print(df['Engine Cylinders'].median())

6.0


In [68]:
# Q6 ..continued..
# Finding Most Frequent Value:

df['Engine Cylinders'].mode()[0]

4.0

In [69]:
# Q6 ..continued..
# Replacing missing values with the most frequnt value:

df['Engine Cylinders'].fillna(df['Engine Cylinders'].mode()[0], inplace=True)

In [71]:
# Q6 ..continued..
# Verifying total missing values after filling the missing values in column 'Engine Cylinders'

df.isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders        0
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [73]:
# Q6 ..continued
# Median value after filling missing values:

print(df['Engine Cylinders'].median())

6.0


### Question 7
* Select all the "Lotus" cars from the dataset.
* Select only columns "Engine HP", "Engine Cylinders".
* Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
* Get the underlying NumPy array. Let's call it X.
* Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the * result XTX.
* Invert XTX.
* Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
* Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
* What's the value of the first element of w?

In [87]:
# Q7

X = df[['Engine HP', 'Engine Cylinders']][df['Make'] == 'Lotus'].drop_duplicates()
X

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [93]:
# Q7

XT = X.T
XT

3912   3913   3918   4216   4257   4259   4262   4292  \
Engine HP         189.0  218.0  217.0  350.0  400.0  276.0  345.0  257.0   
Engine Cylinders    4.0    4.0    4.0    8.0    6.0    6.0    6.0    4.0   

                   4293  
Engine HP         240.0  
Engine Cylinders    4.0

In [89]:
# Q7

y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]
y

[1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [94]:
# Q7

XTX = np.dot(XT , X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [95]:
# Q7

XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [97]:
# Q7

w = np.dot(np.dot(XTX_inv,XT),y)
w

array([  4.59494481, -63.56432501])

### Assigment Complete